### ISSUE TITLE
How to Prepare ADNI Dataset?

### ISSUE THREAD

**Issue by jpsml** [kangluoyao/VAP_Former#1]
Hello, would it be possible to give more details about how I should proceed in order to prepare the ADNI dataset for training? e.g. which specific subjects did you use in your experiments, etc.

**Comment by kangluoyao** [comment]
Hi! Thank you for reaching out! You can collect the dataset in ADNI. I only use the baseline data for each subject in ADNI 1 and ADNI 2. Because of the long time interval, I lost the data I collected. You can build up your own dataset. And you can use SPM12 to preprocess them.
